### ISSUE TITLE
Your demo is broken.

### ISSUE THREAD

**Issue by su-narthur** [darlanmendonca/mosaic-css#1]
https://rawgit.com/darlanmendonca/masonry-css/master/dist/index.html

**Comment by darlanmendonca** [comment]
ohh, thanks man

fixed
https://rawgit.com/darlanmendonca/masonry-css/master/dist/index.html

**Comment by darlanmendonca** [comment]
my bad, using remote images, now I put images on repo

later, I will do a gh-page, :D
